apiVersion: "kubeflow.org/v1alpha1"
kind: "MXJob"
metadata:
  name: "example-dist-job"
spec:
  jobMode: "dist"
  replicaSpecs:
    - replicas: 1
      mxReplicaType: SCHEDULER
      PsRootPort: 9000
      template:
        spec:
          containers:
            - image: jzp1025/mxnet:test
              name: mxnet
              command: ["python"]
              args: ["train_mnist.py"]
              workingDir: "/incubator-mxnet/example/image-classification"
          restartPolicy: OnFailure
    - replicas: 1 
      mxReplicaType: SERVER
      template:
        spec:
          containers:
            - image: jzp1025/mxnet:test
              name: mxnet
              command: ["python"]
              args: ["train_mnist.py"]
              workingDir: "/incubator-mxnet/example/image-classification"
          restartPolicy: OnFailure
    - replicas: 1
      mxReplicaType: WORKER
      template:
        spec:
          containers:
            - image: jzp1025/mxnet:test
              name: mxnet
              command: ["python"]
              args: ["train_mnist.py","--num-epochs=10","--num-layers=2","--kv-store=dist_device_sync"]
              workingDir: "/incubator-mxnet/example/image-classification"
          restartPolicy: OnFailure
