
apiVersion: v1
kind: Pod
metadata:
  name: mxnet-worker2
spec:                       
  restartPolicy: OnFailure              
  containers:
  - name: mxnet
    image: "jzp1025/mxnet:cpu"
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]

